
version_base: 1 
name : "SePS release"
seed : 25
env_args : {}
time_limit : 500
dummy_vecenv : True
central_v : False
clusters : None

env:
  - env1_name  : "rware:rware-tiny-4ag-v2"
  - env2_name  : "rware:rware-small-4ag-v2"
  - env3_name  : "rware:rware-medium-6ag-hard-v2"
  - env4_name  : "rware:rware-tiny-2ag-v2"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d-%H-%M-%S}
  output_subdir: tensorboard
  job:
    chdir: true

network:
  architecture : {"actor": [64, 64],"critic": [64, 64]}
  human_selected_idx : None # like [0, 0, 0, 0, 1, 1, 1, 1] or None - only used for visualisation
  encoder_in : ["agent"]
  decoder_in : ["obs", "act"] # + "z"
  reconstruct : ["next_obs", "rew"]
  hartpart : False
  d_model : 5
  num_heads : 5
  num_layers : 6
  d_ff : 1024
  dropout : 0.1


train:
  lr : 3e-4
  optim_eps : 0.00001
  parallel_envs : 4
  n_steps : 5
  gamma : 0.99
  kl_weight : 0.001
  epochs : 10
  z_features : 10
  algorithm_mode : "ops" # "ops", "iac", "snac", or "snac-a"
  device : cpu
  ops_timestep : 100
  delay : 0
  pretraining_steps : 5000
  update_every_episodes : 3
  total_episodes : 300
  pretraining_episodes : 50
  average_episode_length : 500
  pretraining_times : 1
  batch_size : 128
  total_steps : 100000
  log_interval : 20000
  save_interval : 1000000
  eval_interval : 10000
  entropy_coef : 0.01
  value_loss_coef : 0.5
  use_proper_termination : True
  delay_training : False